---
title: "Step 3 - Data formatting"
author : "Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Defining functions and packages

```{r base, fig.height=6, fig.width=12}

# 1. Source functions ----

source("functions/graphical_par.R")
source("functions/ggsave_perso.R")
source("functions/not_all_na.R")

# 2. Recquired packages ----

library(stringi)
library(stringr)
library(plyr)
library(dplyr)
library(tidyr)
library(lubridate)

# 3. Define the biogeographic area value ----

biogeographic_area <- "Australia"

# 4. Create a vector of needed columns names to check which ones are missing ----

needed_colnames <- c("DatasetID", "Area", "Country", "Archipelago", 
                     "Location", "Site", "Zone", "Latitude", "Longitude", 
                     "Depth", "Year", "Date", "Replicate", "Quadrat", "Method", 
                     "Observer", "Cover", "Tax_ID")

```

# Data cleaning



# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`